#!/usr/bin/env bash
# script to install nginx web server
# script configures home file to show Hello World!

apt-get update
apt-get -y --force-yes install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start

