#!/usr/bin/env bash
# script that install nginx
# script to configure index page
# script defines 404 and redirect

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sed -i "/server_name _;/a add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
service nginx restart
