#!/usr/bin/env bash
# script to make nginx support port 80
service nginx stop
ln -f -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
pkill -SIGKILL -f "usr/sbin/nginx"
