#!/usr/bin/env bash
# script that configures server and change home IP for localhost and facebook

cp /etc/hosts hosts_temp
sed -i s/127.0.0.1/127.0.0.2/g hosts_temp
echo 8.8.8.8	facebook.com >> hosts_temp
sudo cp hosts_temp /etc/hosts

